import { Queue, Worker } from 'bullmq';
import { Redis } from 'ioredis';
import cron from 'node-cron';
import {
  ADOPTION_REPORT_KEY,
  ADOPTION_SESSIONS_KEPT,
  Catalog,
  DEDUP_SCHEME,
  DEDUP_SCHEME_KEY,
  EXTRACTION_SCHEME,
  ID_SCHEME,
  PROJECT_GROUPING,
  SPARSE_VERSION,
  VectorStore,
  analyzeAdoption,
  collectionNameFor,
  createEmbedder,
  getConfig,
  loadMachinesFileIfPresent,
  mirrorClaudeDir,
  runDedupMigration,
  type CachedAdoption,
} from '@atlas/core';
import {
  auditVectorCoverage,
  backfillVectors,
  needsBackfill,
  processScanJob,
  rebuildSparseVectors,
  embedderDowngrade,
  restoreIndexingThreshold,
  sparseRebuildAction,
  type PipelineDeps,
  type ScanJobData,
} from './pipeline.js';
import { SCAN_QUEUE, resolveSelfName, scheduleScans, withSchedulerLock } from './scheduler.js';

/**
 * Indexer entrypoint: migrate catalog, resolve the embedding provider,
 * ensure the Qdrant collection, then run scheduler + BullMQ workers.
 */
/**
 * How much routine reconciliation may embed per tick. Sized so a repair pass
 * cannot monopolise a single-threaded local embedder: at ~1.9s per entry this
 * is a couple of minutes, and whatever is left is picked up next tick.
 */
const RECONCILE_MAX_ENTRIES = 100;

/** How often the deep (scroll-based) coverage audit runs. */
const AUDIT_INTERVAL_MS = 24 * 60 * 60 * 1000;
const COVERAGE_AUDIT_KEY = 'coverage_audit_at';
/**
 * When adoption was last *enqueued*, not last completed. Deliberate: a scan that
 * fails must not re-enqueue itself every five minutes, which is what keying off
 * completion would do.
 */
const ADOPTION_TICK_KEY = 'adoption_enqueued_at';

async function main() {
  const cfg = getConfig();
  const catalog = new Catalog(cfg.databaseUrl);
  await catalog.migrate();
  console.log('[indexer] catalog migrated');

  // Changing how ids are derived changes every dedup_key, so old rows can no
  // longer match new ones: a plain rescan would duplicate the entire catalog
  // rather than update it. Everything here is derived from read-only source
  // files, so dropping and re-parsing is the safe, complete migration.
  // An unset key on a populated catalog means it predates the marker: those
  // rows carry v1 ids. An empty catalog needs nothing.
  // Two independent reasons to rebuild the derived index. Both are safe: every
  // row is regenerated by re-parsing the read-only source mounts.
  //  - id_scheme: how dedup keys and point ids are derived changed, so old
  //    rows can never match new ones and a rescan would duplicate the catalog.
  //  - grouping: how sources are attributed to projects changed, so existing
  //    rows hang off the wrong project.
  const hadEntries = (await catalog.countEntries()) > 0;

  // Each marker guards one rule that turns sources into rows. If any changed,
  // the existing rows were made by the old rule and no rescan will replace
  // them, so the derived index is rebuilt.
  const MARKERS = [
    { key: 'id_scheme', label: 'id scheme', want: ID_SCHEME },
    { key: 'grouping_scheme', label: 'project grouping', want: PROJECT_GROUPING },
    { key: 'extraction_scheme', label: 'session extraction', want: EXTRACTION_SCHEME },
  ];

  let reason: string | null = null;
  for (const m of MARKERS) {
    // An unset marker on a populated catalog means it predates that marker.
    const stored = (await catalog.getSetting(m.key)) || (hadEntries ? 'v1' : m.want);
    if (stored !== m.want && !reason) reason = `${m.label} ${stored} -> ${m.want}`;
  }

  const schemeChanged = reason !== null;
  if (schemeChanged) {
    console.log(
      `[indexer] ${reason}: clearing the derived index ` +
        '(sources are untouched; everything is re-parsed)',
    );
    await catalog.resetDerivedData();
  }
  for (const m of MARKERS) await catalog.setSetting(m.key, m.want);

  // First multi-machine boot: stamp every pre-machine entries/sessions row
  // ('') with this machine's name so provenance is never blank. Idempotent —
  // a healthy boot after the first finds nothing left to stamp.
  const backfilled = await catalog.backfillMachine(resolveSelfName(cfg));
  if (backfilled > 0) {
    console.log(`[indexer] backfilled machine on ${backfilled} pre-machine row(s)`);
  }

  /**
   * Dedup key v3 (spec §6): recompute every key in place from
   * machine-independent identity, so git-synced content stops being indexed
   * once per machine.
   *
   * Its own marker and its own advisory lock, and it runs to completion here —
   * before the embedder, the worker and the cron tick — because every one of
   * those either writes entries or reads keys, and a half-migrated catalog
   * would let a scan insert a duplicate of a row it could no longer match.
   * Nothing is re-embedded: point ids hash the STORED source_path under the
   * frozen v2 namespace, so no vector moves.
   */
  if ((await catalog.getSetting(DEDUP_SCHEME_KEY)) !== DEDUP_SCHEME) {
    if (!hadEntries || schemeChanged) {
      // Nothing to rekey — an empty catalog, or one this boot just truncated.
      // Every row inserted from here on is written with a v3 key already.
      await catalog.setSetting(DEDUP_SCHEME_KEY, DEDUP_SCHEME);
    } else {
      /**
       * A collision loser must lose its Qdrant points BEFORE its Postgres row
       * (spec §6.4), and those points live in the collection search is served
       * from — `active_collection` — not in whatever this boot's embedder
       * resolves to. Unset means nothing was ever published, so nothing was
       * ever embedded: there are no points to delete and the Postgres-only
       * path is complete rather than a shortcut.
       */
      const activeCollection = await catalog.getSetting('active_collection').catch(() => null);
      const migrationVectors = activeCollection
        ? new VectorStore(cfg.qdrantUrl, activeCollection)
        : null;
      // Stored claude paths may sit under this machine's mount or any mirror's;
      // a dir that does not exist costs nothing (identityFromStored falls back
      // to the same <dir>/<file> shape).
      const machinesFile = loadMachinesFileIfPresent(cfg.machinesFile);
      const claudeDirs = [
        cfg.claudeProjectsDir,
        ...(machinesFile?.machines ?? []).map((m) => mirrorClaudeDir(m.name)),
      ];
      console.log('[indexer] dedup key migration v3 starting (in place; no re-embed)');
      const t0 = Date.now();
      const s = await runDedupMigration(catalog, migrationVectors, { claudeDirs });
      console.log(
        `[indexer] dedup v3 done in ${Math.round((Date.now() - t0) / 1000)}s: ${JSON.stringify(s)}`,
      );
    }
  }

  const embedder = await createEmbedder(cfg.embeddings, cfg.g2pClientId);
  console.log(`[indexer] embedder: ${embedder.name}/${embedder.model} dim=${embedder.dim}`);

  const targetCollection = collectionNameFor(embedder.name, embedder.model, embedder.dim);

  // Before anything writes: would this boot move the index somewhere nobody
  // asked for? Checked here rather than later because everything after this
  // point — ensure, backfill, publish, reclaim — is what does the damage.
  const previousCollection = await catalog.getSetting('active_collection').catch(() => null);
  const verdict = embedderDowngrade({
    configuredProvider: cfg.embeddings.provider,
    resolvedName: embedder.name,
    targetCollection,
    activeCollection: previousCollection,
    populatedEntries: previousCollection ? await catalog.countVectorized(previousCollection) : 0,
    allowDowngrade: cfg.allowEmbedderDowngrade,
  });
  if (verdict.refuse) {
    // Exit rather than carry on: `restart: unless-stopped` brings the indexer
    // back, and by then the provider is usually up — the probe retries only
    // cover the first seven seconds. Serving continues throughout, because the
    // API reads `active_collection`, which this refuses to change.
    console.error(`[indexer] REFUSING TO START — ${verdict.reason}`);
    await catalog.close?.().catch(() => {});
    process.exit(1);
  }

  const vectors = new VectorStore(cfg.qdrantUrl, targetCollection);
  if (schemeChanged) {
    // Old points are keyed by the old scheme; they would never be overwritten.
    await vectors.drop();
  }
  await vectors.ensure(embedder.dim);
  await catalog.setSetting('active_embedder', `${embedder.name}/${embedder.model}/${embedder.dim}`);
  console.log(`[indexer] qdrant collection ready: ${vectors.collection}`);

  const deps: PipelineDeps = { catalog, vectors, embedder };
  const connection = new Redis(cfg.redisUrl, { maxRetriesPerRequest: null });
  const queue = new Queue<ScanJobData>(SCAN_QUEUE, { connection });

  // Scan jobs carry deterministic ids and BullMQ retains completed jobs, so
  // re-adding an id it has already run is a silent no-op. Once the catalog is
  // wiped, the queue's memory of "already scanned this" is a lie and every new
  // job is swallowed. The two must be reset together.
  if (schemeChanged) {
    await queue.obliterate({ force: true });
    console.log('[indexer] scan queue cleared so every source is rescanned');
  }

  /**
   * Release job ids held by past failures.
   *
   * `removeOnFail: true` stops new ones accumulating, but it cannot free the
   * ids already reserved — and a reserved id is not a stale entry, it is a
   * source that will never be scanned again. On 2026-07-29 that was 48 of them,
   * one per source, all failed during a single Postgres restart three days
   * earlier: every project except deepcast had silently stopped indexing while
   * the scheduler went on reporting 140 jobs enqueued a tick.
   *
   * Kept on every boot rather than made a one-off migration. It is a no-op once
   * nothing is retained, and the failure it repairs is invisible from the
   * outside — which is the argument for repairing it unconditionally rather
   * than trusting that it cannot come back.
   */
  try {
    const released = await queue.clean(0, 10_000, 'failed');
    if (released.length) {
      console.log(
        `[indexer] released ${released.length} scan job id(s) held by past failures — ` +
          'those sources can be scanned again',
      );
    }
  } catch (e) {
    console.warn(`[indexer] could not clean failed jobs: ${(e as Error).message}`);
  }

  /**
   * Any entry not embedded into the active collection is unsearchable, and a
   * normal scan will never fix it: entries are never re-inserted (dedup_key),
   * so nothing re-emits them. Vectors must be rebuilt from Postgres.
   *
   * One count covers both causes. A model switch changes the collection name
   * (it encodes the dimension), so every row's `vectorized_in` goes stale at
   * once and this rebuilds everything. An embedder outage leaves a handful
   * stale and this repairs just those.
   *
   * This runs to completion *before* the scan worker starts. Both paths embed,
   * and a local Ollama serves one request at a time, so letting them compete
   * starves the backfill (measured: ~70s per batch against 0.7s standalone).
   *
   * `active_collection` is only published once the rebuild finishes, so the
   * API keeps querying the previous, fully-populated collection throughout.
   */
  /**
   * Audit before trusting the column, but only when it claims something is
   * missing. On a healthy boot the count is 0 and the scroll is skipped
   * entirely; when the column is newly added every row reads as uncovered, and
   * the audit adopts the vectors that already exist instead of letting the
   * indexer re-embed the whole catalog for hours.
   */
  let uncovered = await catalog.countUncovered(vectors.collection);
  if (uncovered > 0) {
    const { adopted, cleared, partial } = await auditVectorCoverage(deps);
    // Counts are the *delta* the audit wrote, not totals: "adopted" is rows
    // whose vectors were already present but unmarked, "cleared" is rows marked
    // covered whose points are gone. Both zero means the column already matched
    // the collection and the uncovered entries are genuinely unembedded.
    //
    // `partial` is called out separately because it is the one with no innocent
    // explanation: total loss follows a dropped collection or a restore, while a
    // half-embedded entry means writes were accepted and then lost.
    console.log(
      `[indexer] coverage audit: adopted ${adopted}, cleared ${cleared}` +
        (partial ? ` (${partial} of them only PARTLY embedded)` : '') +
        ` (against ${vectors.collection})`,
    );
    uncovered = await catalog.countUncovered(vectors.collection);
  }
  const rebuilding = needsBackfill(uncovered);
  // Captured before the backfill consumes them: `sparseRebuildAction` needs to
  // know how much of the collection this boot rewrote, and `uncovered` is a
  // pre-backfill fact that stops being true the moment the backfill runs.
  const uncoveredAtBoot = uncovered;
  const totalEntriesAtBoot = await catalog.countEntries();
  if (rebuilding) {
    const previous = await catalog.getSetting('active_collection');
    console.log(
      `[indexer] ${uncovered} entries are not searchable in ${vectors.collection} — ` +
        `re-embedding from the catalog${previous ? ` (search stays on ${previous})` : ''}`,
    );
    const t0 = Date.now();
    const n = await backfillVectors(deps, {
      // Throughput comes from `embedded` (this run); the bar uses `done`
      // (absolute), or a resumed run would report an absurd rate.
      onPage: async (done, total, embedded) => {
        const rate = embedded / Math.max(1, (Date.now() - t0) / 1000);
        const etaSec = Math.round((total - done) / Math.max(rate, 0.01));
        // Surfaced by /api/stats so a stalled rebuild is visible in the UI
        // rather than only in `docker logs`.
        await catalog
          .setSetting('backfill', JSON.stringify({ done, total, etaSec }))
          .catch(() => {});
        if (done % 2000 < 200) {
          console.log(`[indexer] re-embed ${done}/${total} entries (~${Math.round(etaSec / 60)}m left)`);
        }
      },
    });
    await catalog.setSetting('backfill', '').catch(() => {});
    console.log(`[indexer] re-embed complete: ${n} entries in ${Math.round((Date.now() - t0) / 1000)}s`);
  }

  // Publish only now: readers switch to the new collection once it can serve.
  await catalog.setSetting('active_collection', vectors.collection);

  /**
   * Re-tokenise the sparse side when the tokeniser has changed under it.
   *
   * Query vectors and stored vectors must come from the same tokeniser. When
   * they do not, keyword search does not error — it silently stops matching,
   * which is how a question about a "6.8MB json" came back with all five entries
   * that answered it nowhere in the top 100 (2026-07-29).
   *
   * Keyed per collection, like the quantization marker. Runs after
   * `active_collection` is published because it does not degrade what it touches
   * — a point keeps serving its old sparse vector until the moment the new one
   * lands, and dense retrieval never changes.
   *
   * The decision itself lives in `sparseRebuildAction`, as a pure function: the
   * inline version of it was silently wrong (see that function's note).
   */
  // A rebuild killed mid-pass leaves HNSW building switched off, which nothing
  // would report: dense search stays correct, just served by exact scan.
  if (await restoreIndexingThreshold(deps).catch(() => false)) {
    console.warn('[indexer] restored HNSW indexing left suspended by an interrupted sparse rebuild');
  }

  const sparseKey = `sparse_version:${vectors.collection}`;
  // Keyed by target version as well as collection: a cursor left behind by an
  // interrupted pass to v2 says nothing about how far a pass to v3 has got, and
  // resuming from it would skip every entry below it at the new version.
  const cursorKey = `sparse_cursor:${vectors.collection}:${SPARSE_VERSION}`;
  const storedSparse = Number(await catalog.getSetting(sparseKey).catch(() => null)) || 0;
  const sparseAction = sparseRebuildAction({
    storedVersion: storedSparse,
    currentVersion: SPARSE_VERSION,
    uncovered: uncoveredAtBoot,
    totalEntries: totalEntriesAtBoot,
    backfilled: rebuilding,
    enabled: cfg.sparseRebuild,
  });
  if (sparseAction !== 'none') {
    if (sparseAction === 'stamp') {
      await catalog.setSetting(sparseKey, String(SPARSE_VERSION)).catch(() => {});
      console.log(
        `[indexer] sparse v${SPARSE_VERSION} written by the full rebuild — no re-tokenise needed`,
      );
    } else if (sparseAction === 'skipped') {
      console.warn(
        `[indexer] sparse re-tokenise to v${SPARSE_VERSION} SKIPPED (KDB_SPARSE_REBUILD=false). ` +
          'Keyword search is running on stale tokens until it is allowed to run.',
      );
    } else {
      // Resume where an interrupted pass stopped rather than redoing finished
      // pages; a fresh pass starts at 0 because the cursor is cleared on success.
      const resume = Number(await catalog.getSetting(cursorKey).catch(() => null)) || 0;
      const t0 = Date.now();
      console.log(
        `[indexer] re-tokenising sparse vectors to v${SPARSE_VERSION}` +
          `${resume ? ` (resuming after entry ${resume})` : ''} — no embedding calls`,
      );
      const { entries, points, skipped } = await rebuildSparseVectors(deps, {
        startCursor: resume,
        onPage: async (done, total, cursor) => {
          await catalog.setSetting(cursorKey, String(cursor)).catch(() => {});
          if (done % 10_000 < 500) console.log(`[indexer] re-tokenise ${done}/${total} entries`);
        },
      });
      // Stamp only on a completed pass. A crash mid-pass leaves the version
      // unset, so the next boot resumes instead of calling a half-rebuilt
      // index good.
      await catalog.setSetting(sparseKey, String(SPARSE_VERSION)).catch(() => {});
      await catalog.setSetting(cursorKey, '').catch(() => {});
      console.log(
        `[indexer] re-tokenise complete: ${entries} entries / ${points} points ` +
          `in ${Math.round((Date.now() - t0) / 1000)}s` +
          (skipped ? ` — ${skipped} points REJECTED (stale ids; see index errors)` : '') +
          '. Writes are durable; Qdrant applies them to search over the next few minutes.',
      );
    }
  }

  // Retrofit the memory layout (int8 quantization + vectors and sparse index
  // on disk) onto the live collection once. Guarded by a marker keyed to the
  // collection so it runs a single time per collection and never on every
  // boot. Done AFTER the collection is published and any backfill finished, so
  // search is already serving from it. Best-effort: a transient Qdrant hiccup
  // here must not stop the indexer from scanning.
  //
  // The marker is VERSIONED, not a boolean. v1 meant "quantization applied";
  // v2 adds the on_disk conversion that v1 was supposed to have delivered and
  // silently did not (see VECTORS in qdrant.ts). A collection stamped v1 still
  // needs converting, so the inequality is what re-runs it — a plain truthiness
  // check would skip exactly the collections that need the fix most.
  //
  // v3 (2026-08-14) carries the corrected OPTIMIZERS.max_segment_size. That
  // constant was in the wrong unit (KB-of-256-dim-vectors, not vectors), which
  // held the live collection at 23 segments instead of its 8-segment target and
  // cost 385.9 MB in fixed per-segment null-index padding — two 1 MiB
  // flags_a.dat mmaps per indexed field per segment, 64% of the whole payload
  // index. Fixing the constant alone would have been INERT here: createCollection
  // only runs for a collection that does not exist, and this one is already
  // stamped v2, so nothing would ever have pushed the new value at it. The bump
  // is what makes the fix reach live data.
  //
  // Cheap: vectors, sparse and quantization are already in their target state,
  // so that part of the PATCH is a no-op, and the optimizer change is metadata.
  // The merging that follows is real work but bounded by
  // max_optimization_threads: 2.
  const layoutKey = `quantized:${vectors.collection}`;
  const LAYOUT_VERSION = 'v3';
  if ((await catalog.getSetting(layoutKey).catch(() => null)) !== LAYOUT_VERSION) {
    try {
      await vectors.ensureStorageLayout();
      await catalog.setSetting(layoutKey, LAYOUT_VERSION).catch(() => {});
      console.log(`[indexer] storage layout (int8 + on-disk vectors) applied to ${vectors.collection}`);
    } catch (e) {
      console.warn(
        `[indexer] could not apply storage layout (will retry next boot): ${(e as Error).message}`,
      );
    }
  }

  // Reclaim collections left behind by past model switches. Keeps the active
  // collection and the one this embedder writes to (identical here, but the
  // pair is explicit so a future divergence can't drop a live collection).
  // Only ever touches our own COLLECTION_PREFIX names.
  try {
    const active = (await catalog.getSetting('active_collection')) ?? vectors.collection;
    const dropped = await vectors.reclaimOrphans([active, vectors.collection]);
    if (dropped.length) console.log(`[indexer] reclaimed orphaned collections: ${dropped.join(', ')}`);
  } catch (e) {
    console.warn(`[indexer] orphan reclaim skipped: ${(e as Error).message}`);
  }

  const worker = new Worker<ScanJobData>(
    SCAN_QUEUE,
    async (job) => {
      // Manual trigger from the API: expand into per-project scan jobs.
      const data = job.data as ScanJobData & { trigger?: string; project?: string };
      /**
       * Continuous repair. Runs as a queued job rather than inline in the cron
       * tick because it embeds: the tick holds a 55s scheduler lock, while a
       * reconcile can take minutes. As a job it gets BullMQ's lock renewal and
       * competes for the worker slot like any other embedding work.
       */
      if (data.trigger === 'reconcile') {
        // The deep audit is the only thing that can see vectors lost on the
        // Qdrant side, where the column still claims coverage is complete — so
        // it must run on its own schedule, not merely when something looks off.
        const lastAudit = Number(await catalog.getSetting(COVERAGE_AUDIT_KEY).catch(() => null)) || 0;
        if (Date.now() - lastAudit > AUDIT_INTERVAL_MS) {
          const { adopted, cleared, partial } = await auditVectorCoverage(deps);
          await catalog.setSetting(COVERAGE_AUDIT_KEY, String(Date.now())).catch(() => {});
          if (adopted || cleared) {
            console.warn(
              `[indexer] coverage audit corrected the catalog: adopted ${adopted}, cleared ${cleared}` +
                (partial ? ` (${partial} only PARTLY embedded)` : ''),
            );
          }
        }

        const uncovered = await catalog.countUncovered(vectors.collection);
        if (!uncovered) return { reconciled: 0 };
        // Loud: entries in this state are invisible to search, which is exactly
        // the failure that went unnoticed on 2026-07-25. A status field nobody
        // reads is not detection.
        console.warn(
          `[indexer] ${uncovered} entries are not searchable in ${vectors.collection} — reconciling`,
        );
        const reconciled = await backfillVectors(deps, {
          maxEntries: RECONCILE_MAX_ENTRIES,
          onPage: async (done) => {
            await job.updateProgress({ file: 'reconcile', chunks: done }).catch(() => {});
          },
        });
        console.log(
          `[indexer] reconciled ${reconciled} entries (${Math.max(0, uncovered - reconciled)} left)`,
        );
        return { reconciled };
      }
      if (data.trigger === 'manual') {
        const runId = await catalog.startRun('manual');
        const enqueued = await scheduleScans(cfg, catalog, queue, {
          project: data.project,
          full: data.full,
        });
        await catalog.finishRun(runId, { enqueued });
        return { enqueued };
      }
      /**
       * Tool adoption. Runs here rather than in the API because it reads every
       * Claude transcript on the machine and only this container mounts them.
       * As a queued job it also gets BullMQ's lock renewal, which a multi-minute
       * scan needs, and it never competes with a request for its own answer.
       */
      if (data.trigger === 'adoption') {
        const t0 = Date.now();
        const report = await analyzeAdoption({ root: cfg.claudeProjectsDir });
        // The full session list is long and its tail is a list nobody reads.
        // Capping keeps the cached blob small without touching the aggregates,
        // which are computed over every session either way.
        const payload: CachedAdoption = {
          report: { ...report, sessions: report.sessions.slice(0, ADOPTION_SESSIONS_KEPT) },
          computedAt: new Date().toISOString(),
          tookMs: Date.now() - t0,
        };
        await catalog.setSetting(ADOPTION_REPORT_KEY, JSON.stringify(payload));
        console.log(
          `[indexer] adoption: ${report.sessionsScanned} sessions scanned in ${payload.tookMs}ms`,
        );
        return { sessionsScanned: report.sessionsScanned };
      }
      const t0 = Date.now();
      // updateProgress renews the job lock; without it, files that take longer
      // than lockDuration trip BullMQ's stall watchdog and get re-queued.
      const { chunksIndexed } = await processScanJob(deps, job.data, async ({ file, chunks }) => {
        await job.updateProgress({ file, chunks }).catch(() => {});
      });
      if (chunksIndexed > 0) {
        console.log(
          `[indexer] ${job.data.projectSlug}/${job.data.sourceType}: +${chunksIndexed} chunks in ${Date.now() - t0}ms`,
        );
      }
      return { chunksIndexed };
    },
    {
      connection: new Redis(cfg.redisUrl, { maxRetriesPerRequest: null }),
      concurrency: cfg.workerConcurrency,
      // Embedding a batch on CPU can take a while; give the lock room and let
      // updateProgress() renew it. Defaults (30s/1) are tuned for fast jobs.
      lockDuration: 120_000,
      stalledInterval: 120_000,
      maxStalledCount: 3,
    },
  );
  worker.on('failed', (job, err) => {
    console.error(`[indexer] job ${job?.id} failed: ${err.message}`);
  });

  const tick = async (kind: 'boot' | 'scheduled') => {
    await withSchedulerLock(connection, async () => {
      const runId = await catalog.startRun(kind);
      const enqueued = await scheduleScans(cfg, catalog, queue);
      // Always enqueued: the job itself decides whether there is anything to do.
      // Deciding here would mean the cheap `countUncovered` check gates the deep
      // audit too, and the audit exists precisely for the case where the column
      // wrongly reports full coverage.
      await queue.add(
        'reconcile',
        { trigger: 'reconcile' } as unknown as ScanJobData,
        // A fixed id collapses duplicates while one is still pending, so a slow
        // reconcile cannot accumulate a queue of copies of itself. It must be
        // released on failure as well as on success — a retained id is a
        // reserved id whatever state retains it, and 'reconcile' spent three
        // days in the failed set on 2026-07-29 for exactly that reason.
        { jobId: 'reconcile', removeOnComplete: true, removeOnFail: true, attempts: 1 },
      );
      await catalog.finishRun(runId, { enqueued });
      console.log(`[indexer] ${kind} tick: ${enqueued} scan jobs enqueued`);

      /**
       * Adoption on its own, much slower clock. It scans every transcript on the
       * machine, and the answer — whether agents call Atlas when a trigger fires
       * — moves over days, not minutes. Enqueuing it on every 5-minute tick
       * would spend hours of CPU restating the same number.
       *
       * Staleness is checked here rather than in the job so a fixed jobId can
       * still collapse duplicates: the check is what keeps the queue from seeing
       * a candidate at all.
       */
      const last = Number(await catalog.getSetting(ADOPTION_TICK_KEY).catch(() => null)) || 0;
      if (Date.now() - last > cfg.adoptionRefreshMin * 60_000) {
        await catalog.setSetting(ADOPTION_TICK_KEY, String(Date.now())).catch(() => {});
        await queue.add('adoption', { trigger: 'adoption' } as unknown as ScanJobData, {
          jobId: 'adoption',
          removeOnComplete: true,
          removeOnFail: true,
          attempts: 1,
        });
      }
    });
  };

  await tick('boot');
  cron.schedule(`*/${cfg.scanIntervalMin} * * * *`, () => {
    tick('scheduled').catch((e) => console.error('[indexer] tick failed:', e));
  });

  const shutdown = async () => {
    console.log('[indexer] shutting down…');
    await worker.close();
    await queue.close();
    connection.disconnect();
    await catalog.close();
    process.exit(0);
  };
  process.on('SIGTERM', shutdown);
  process.on('SIGINT', shutdown);
}

main().catch((e) => {
  console.error('[indexer] fatal:', e);
  process.exit(1);
});
